
create table pktype (
  id int primary key auto_increment not null,
  type varchar(50) not null,
  icon varchar(255) not null
);

create table pokemon (
  id int primary key auto_increment not null,
  name varchar(50) not null,
  description varchar(255) not null,
  image varchar(255) not null,
  type_id int,
  FOREIGN KEY (type_id) REFERENCES pktype(id)
);

INSERT INTO pktype (type, icon) VALUES
('Grass', 'http://www.rw-designer.com/icon-view/21171.png'),
('Fire', 'http://www.rw-designer.com/icon-view/21169.png'),
('Water', 'http://www.rw-designer.com/icon-view/21170.png'),
('Bug', 'http://www.rw-designer.com/icon-view/21178.png'),
('Normal', 'http://www.rw-designer.com/icon-view/21168.png'),
('Flying', 'http://www.rw-designer.com/icon-view/21175.png'),
('Poison', 'http://www.rw-designer.com/icon-view/21183.png'),
('Electric', 'http://www.rw-designer.com/icon-view/21179.png'),
('Ground', 'http://www.rw-designer.com/icon-view/21172.png'),
('Psychic', 'http://www.rw-designer.com/icon-view/21185.png'),
('Fighting', 'http://www.rw-designer.com/icon-view/21181.png'),
('Rock', 'http://www.rw-designer.com/icon-view/21174.png'),
('Ghost', 'http://www.rw-designer.com/icon-view/21187.png'),
('Ice', 'http://www.rw-designer.com/icon-view/21176.png'),
('Dragon', 'http://www.rw-designer.com/icon-view/21189.png'),
('Steel', 'http://www.rw-designer.com/icon-view/21180.png'),
('Dark', 'http://www.rw-designer.com/icon-view/21184.png'),
('Fairy', 'http://www.rw-designer.com/icon-view/21188.png');


INSERT INTO pokemon (name, description, image, type_id) VALUES
('Bulbasaur', 'A grass/poison-type Pokemon with a plant bulb on its back.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png', 1),
('Ivysaur', 'The evolved form of Bulbasaur, Ivysaur has a larger plant bulb and more developed vines.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png', 1),
('Venusaur', 'The final evolution of Bulbasaur, Venusaur is a large and powerful grass/poison-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png', 1),
('Charmander', 'A fire-type Pokemon with a flame at the tip of its tail. It evolves into Charmeleon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png', 2),
('Charmeleon', 'The evolved form of Charmander, Charmeleon is a more aggressive fire-type Pokemon with a larger flame.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png', 2),
('Charizard', 'The final evolution of Charmander, Charizard is a powerful fire/flying-type Pokemon with dragon-like features.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png', 2),
('Squirtle', 'A water-type Pokemon known for its water gun attacks. It evolves into Wartortle.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png', 3),
('Wartortle', 'The evolved form of Squirtle, Wartortle is a more formidable water-type Pokemon with larger cannons on its back.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png', 3),
('Blastoise', 'The final evolution of Squirtle, Blastoise is a powerful water-type Pokemon with massive water cannons on its back.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png', 3),
('Caterpie', 'A bug-type Pokemon with a voracious appetite for leaves. It evolves into Metapod.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png', 4),
('Metapod', 'The evolved form of Caterpie, Metapod is in a chrysalis state and cannot move much.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png', 4),
('Butterfree', 'The final evolution of Caterpie, Butterfree is a graceful bug/flying-type Pokemon with colorful wings.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png', 4),
('Weedle', 'A poison/bug-type Pokemon with a sharp stinger on its head. It evolves into Kakuna.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png', 7),
('Kakuna', 'The evolved form of Weedle, Kakuna is in a chrysalis state and is mostly immobile.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png', 7),
('Beedrill', 'The final evolution of Weedle, Beedrill is a large and aggressive poison/bug-type Pokemon with a drill-like stinger.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png', 7),
('Pidgey', 'A normal/flying-type Pokemon that is small but has a large appetite. It evolves into Pidgeotto.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png', 6),
('Pidgeotto', 'The evolved form of Pidgey, Pidgeotto is a larger and more powerful normal/flying-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png', 6),
('Pidgeot', 'The final evolution of Pidgey, Pidgeot is a majestic normal/flying-type Pokemon with impressive wings.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png', 6),
('Rattata', 'A normal-type Pokemon with sharp incisors. It is known for its quickness and agility.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png', 5),
('Raticate', 'The evolved form of Rattata, Raticate is a larger and more aggressive normal-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png', 5),
('Spearow', 'A normal/flying-type Pokemon with a keen eye for detecting prey. It evolves into Fearow.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png', 6),
('Fearow', 'The evolved form of Spearow, Fearow is a large and powerful normal/flying-type Pokemon with a long beak.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png', 6),
('Ekans', 'A poison-type Pokemon known for coiling itself. It evolves into Arbok.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png', 7),
('Arbok', 'The evolved form of Ekans, Arbok is a large and intimidating poison-type Pokemon with a hood-like pattern on its neck.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png', 7),
('Pikachu', 'An electric-type Pokemon with a knack for generating electricity. It evolves from Pichu.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png', 8),
('Raichu', 'The evolved form of Pikachu, Raichu is a larger and more powerful electric-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png', 8),
('Sandshrew', 'A ground-type Pokemon known for its burrowing abilities.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png', 9),
('Sandslash', 'The evolved form of Sandshrew, Sandslash has tough claws and excels in digging.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png', 9),
('Nidoran♀', 'A poison-type Pokemon with a gentle disposition. It evolves into Nidorina.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png', 7),
('Nidorina', 'The evolved form of Nidoran♀, Nidorina is a poison-type Pokemon with increased strength.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png', 7),
('Nidoqueen', 'The final evolution of Nidoran♀, Nidoqueen is a powerful poison/ground-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png', 7),
('Nidoran♂', 'A poison-type Pokemon with a horn on its head. It evolves into Nidorino.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png', 7),
('Nidorino', 'The evolved form of Nidoran♂, Nidorino is a poison-type Pokemon with increased aggression.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png', 7),
('Nidoking', 'The final evolution of Nidoran♂, Nidoking is a powerful poison/ground-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png', 7),
('Clefairy', 'A fairy-type Pokemon known for its cuteness. It evolves from Cleffa.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png', 18),
('Clefable', 'The evolved form of Clefairy, Clefable is a gentle and powerful fairy-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png', 18),
('Vulpix', 'A fire-type Pokemon with six orange tails. It evolves into Ninetales.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png', 2),
('Ninetales', 'The evolved form of Vulpix, Ninetales is a mystical fire-type Pokemon with nine elegant tails.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png', 2),
('Jigglypuff', 'A normal/fairy-type Pokemon known for its ability to put opponents to sleep with its singing.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png', 5),
('Wigglytuff', 'The evolved form of Jigglypuff, Wigglytuff is a large and powerful normal/fairy-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png', 5),
('Zubat', 'A poison/flying-type Pokemon that navigates in the dark using echolocation.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png', 7),
('Golbat', 'The evolved form of Zubat, Golbat is a larger and more menacing poison/flying-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png', 7),
('Oddish', 'A grass/poison-type Pokemon that emits a sweet scent. It evolves into Gloom.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png', 1),
('Gloom', 'The evolved form of Oddish, Gloom is a grass/poison-type Pokemon with a more pungent odor.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png', 1),
('Vileplume', 'The final evolution of Oddish, Vileplume is a large and vibrant grass/poison-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png', 1),
('Paras', 'A bug/grass-type Pokemon that grows parasitic mushrooms on its back.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png', 4),
('Parasect', 'The evolved form of Paras, Parasect is a bug/grass-type Pokemon controlled by the parasitic mushrooms on its back.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png', 4),
('Venonat', 'A bug/poison-type Pokemon covered in purple fur. It evolves into Venomoth.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png', 4),
('Venomoth', 'The evolved form of Venonat, Venomoth is a large and agile bug/poison-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png', 4),
('Diglett', 'A ground-type Pokemon that burrows through the earth at a shallow depth.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png', 9),
('Dugtrio', 'The evolved form of Diglett, Dugtrio is a trio of ground-type Pokemon that share a deep connection.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png', 9),
('Meowth', 'A normal-type Pokemon known for its mischievous behavior and its ability to pick up coins.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png', 5),
('Persian', 'The evolved form of Meowth, Persian is an elegant and swift normal-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png', 5),
('Psyduck', 'A water-type Pokemon with a constant headache. It evolves into Golduck.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png', 3),
('Golduck', 'The evolved form of Psyduck, Golduck is a powerful and graceful water-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png', 3),
('Mankey', 'A fighting-type Pokemon with a short temper. It evolves into Primeape.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png', 11),
('Primeape', 'The evolved form of Mankey, Primeape is a highly aggressive fighting-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png', 11),
('Growlithe', 'A fire-type Pokemon known for its loyalty. It evolves into Arcanine.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png', 2),
('Arcanine', 'The evolved form of Growlithe, Arcanine is a majestic and powerful fire-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png', 2),
('Poliwag', 'A water-type Pokemon with a swirl pattern on its belly. It evolves into Poliwhirl.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png', 3),
('Poliwhirl', 'The evolved form of Poliwag, Poliwhirl is a more developed water-type Pokemon with longer limbs.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png', 3),
('Poliwrath', 'The evolved form of Poliwhirl, Poliwrath is a powerful water/fighting-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png', 3),
('Abra', 'A psychic-type Pokemon known for its ability to teleport away from danger. It evolves into Kadabra.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png', 10),
('Kadabra', 'The evolved form of Abra, Kadabra is a psychic-type Pokemon with enhanced psychic abilities.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png', 10),
('Alakazam', 'The final evolution of Abra, Alakazam is a highly intelligent and powerful psychic-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png', 10),
('Machop', 'A fighting-type Pokemon with impressive strength. It evolves into Machoke.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png', 11),
('Machoke', 'The evolved form of Machop, Machoke is a muscular fighting-type Pokemon in the midst of training.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png', 11),
('Machamp', 'The final evolution of Machop, Machamp is a four-armed fighting-type Pokemon with incredible power.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png', 11),
('Bellsprout', 'A grass/poison-type Pokemon with a bell-shaped head. It evolves into Weepinbell.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png', 1),
('Weepinbell', 'The evolved form of Bellsprout, Weepinbell is a larger and more menacing grass/poison-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png', 1),
('Victreebel', 'The final evolution of Bellsprout, Victreebel is a carnivorous plant Pokemon with a large mouth.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png', 1),
('Tentacool', 'A water/poison-type Pokemon with tentacles that sting. It evolves into Tentacruel.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png', 3),
('Tentacruel', 'The evolved form of Tentacool, Tentacruel is a large and powerful water/poison-type Pokemon with numerous tentacles.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png', 3),
('Geodude', 'A rock/ground-type Pokemon with a rocky appearance. It evolves into Graveler.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png', 12),
('Graveler', 'The evolved form of Geodude, Graveler is a rugged rock/ground-type Pokemon with a sturdy exterior.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png', 12),
('Golem', 'The final evolution of Geodude, Golem is a massive rock/ground-type Pokemon known for its incredible strength.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png', 12),
('Ponyta', 'A fire-type Pokemon with a mane of flames. It evolves into Rapidash.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png', 2),
('Rapidash', 'The evolved form of Ponyta, Rapidash is a majestic fire-type Pokemon with incredible speed and agility.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png', 2),
('Slowpoke', 'A water/psychic-type Pokemon known for its slow movements. It evolves into Slowbro.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png', 3),
('Slowbro', 'The evolved form of Slowpoke, Slowbro is a water/psychic-type Pokemon with a Shellder attached to its tail.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png', 3),
('Magnemite', 'An electric/steel-type Pokemon with magnets on its sides. It evolves into Magneton.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png', 17),
('Magneton', 'The evolved form of Magnemite, Magneton is a cluster of three Magnemite linked by strong magnetic forces.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/082.png', 17),
('Farfetch’d', 'A normal/flying-type Pokemon that carries a leek stalk as its weapon. It evolves into Sirfetch’d.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/083.png', 6),
('Doduo', 'A normal/flying-type Pokemon with two heads. It evolves into Dodrio.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/084.png', 6),
('Dodrio', 'The evolved form of Doduo, Dodrio is a three-headed normal/flying-type Pokemon known for its speed.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/085.png', 6),
('Seel', 'A water-type Pokemon with a seal-like appearance. It evolves into Dewgong.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/086.png', 3),
('Dewgong', 'The evolved form of Seel, Dewgong is a water/ice-type Pokemon known for its graceful swimming.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/087.png', 3),
('Grimer', 'A poison-type Pokemon with a slimy, sludgy appearance. It evolves into Muk.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/088.png', 7),
('Muk', 'The evolved form of Grimer, Muk is a large and amorphous poison-type Pokemon made of toxic sludge.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png', 7),
('Shellder', 'A water-type Pokemon with a protective shell. It evolves into Cloyster.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/090.png', 3),
('Cloyster', 'The evolved form of Shellder, Cloyster is a water/ice-type Pokemon with a durable and icy shell.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/091.png', 3),
('Gastly', 'A ghost/poison-type Pokemon known for its mischievous behavior. It evolves into Haunter.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png', 13),
('Haunter', 'The evolved form of Gastly, Haunter is a ghost/poison-type Pokemon that enjoys scaring people.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/093.png', 13),
('Gengar', 'The final evolution of Gastly, Gengar is a powerful ghost/poison-type Pokemon known for its mischievous and sinister nature.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png', 13),
('Onix', 'A rock/ground-type Pokemon with a serpentine appearance. It evolves into Steelix when traded holding a Metal Coat.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png', 12),
('Drowzee', 'A psychic-type Pokemon that can put opponents to sleep with its psychic powers. It evolves into Hypno.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png', 10),
('Hypno', 'The evolved form of Drowzee, Hypno is a psychic-type Pokemon known for its powerful hypnotic abilities.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/097.png', 10),
('Krabby', 'A water-type Pokemon with a crab-like appearance. It evolves into Kingler.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/098.png', 3),
('Kingler', 'The evolved form of Krabby, Kingler is a large and powerful water-type Pokemon with massive claws.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/099.png', 3),
('Voltorb', 'An electric-type Pokemon that resembles a Poké Ball. It evolves into Electrode.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/100.png', 8),
('Electrode', 'The evolved form of Voltorb, Electrode is a fast and explosive electric-type Pokemon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/101.png', 8),
('Exeggcute', 'A grass/psychic-type Pokemon consisting of six eggs. It evolves into Exeggutor.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png', 1),
('Exeggutor', 'The evolved form of Exeggcute, Exeggutor is a large and majestic grass/psychic-type Pokemon with multiple heads.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png', 1),
('Cubone', 'A ground-type Pokemon that wears a skull as a helmet. It evolves into Marowak.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png', 9),
('Marowak', 'The evolved form of Cubone, Marowak is a ground-type Pokemon known for its loyalty to its deceased mother.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png', 9),
('Hitmonlee', 'A fighting-type Pokemon known for its powerful kicks. It is one of the two possible evolutions of Tyrogue.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png', 11),
('Hitmonchan', 'A fighting-type Pokemon known for its swift punches. It is one of the two possible evolutions of Tyrogue.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/107.png', 11),
('Lickitung', 'A normal-type Pokemon with a long, sticky tongue. It evolves into Lickilicky when leveled up while knowing the move Rollout.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png', 5),
('Koffing', 'A poison-type Pokemon that emits toxic gases. It evolves into Weezing.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/109.png', 7),
('Weezing', 'The evolved form of Koffing, Weezing is a larger and more menacing poison-type Pokemon with two heads.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/110.png', 7),
('Rhyhorn', 'A ground/rock-type Pokemon with a tough hide. It evolves into Rhydon.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/111.png', 12),
('Rhydon', 'The evolved form of Rhyhorn, Rhydon is a powerful ground/rock-type Pokemon known for its durability.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/112.png', 12),
('Chansey', 'A normal-type Pokemon known for its incredible ability to heal wounds. It evolves from Happiny when leveled up holding an Oval Stone during the day.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png', 5),
('Tangela', 'A grass-type Pokemon with vines that can stretch and entangle foes. It evolves into Tangrowth when leveled up knowing the move Ancient Power.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/114.png', 1),
('Kangaskhan', 'A normal-type Pokemon known for its maternal instincts. It is the final evolution of Cubone.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png', 5),
('Horsea', 'A water-type Pokemon resembling a small seahorse. It evolves into Seadra when leveled up holding a Dragon Scale.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/116.png', 3),
('Seadra', 'The evolved form of Horsea, Seadra is a water-type Pokemon with enhanced swimming abilities.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png', 3),
('Goldeen', 'A water-type Pokemon with a horn on its head. It evolves into Seaking.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/118.png', 3),
('Seaking', 'The evolved form of Goldeen, Seaking is a powerful water-type Pokemon known for its swift swimming.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/119.png', 3),
('Staryu', 'A water-type Pokemon with a star-shaped body. It evolves into Starmie.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/120.png', 3),
('Starmie', 'The evolved form of Staryu, Starmie is a water/psychic-type Pokemon with enhanced psychic abilities.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png', 3),
('Mr. Mime', 'A psychic/fairy-type Pokemon known for its ability to create invisible objects. It evolves from Mime Jr. when leveled up knowing the move Mimic.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png', 10),
('Scyther', 'A bug/flying-type Pokemon with scythes for hands. It evolves into Scizor when traded holding a Metal Coat.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/123.png', 7),
('Jynx', 'An ice/psychic-type Pokemon known for its graceful and dance-like movements. It evolves from Smoochum when leveled up knowing the move Powder Snow.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/124.png', 14),
('Electabuzz', 'An electric-type Pokemon that generates electricity in its body. It evolves into Electivire when traded holding an Electirizer.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png', 8),
('Magmar', 'A fire-type Pokemon with a body temperature of over 2,200 degrees Fahrenheit. It evolves into Magmortar when traded holding a Magmarizer.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/126.png', 2),
('Pinsir', 'A bug-type Pokemon with powerful pincers. It Mega Evolves into Mega Pinsir using a Pinsirite.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/127.png', 7),
('Tauros', 'A normal-type Pokemon known for its aggressive nature. It is exclusive to the Safari Zone in certain regions.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/128.png', 5),
('Magikarp', 'A weak and pathetic water-type Pokemon that evolves into Gyarados.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png', 3),
('Gyarados', 'The evolved form of Magikarp, Gyarados is a powerful water/flying-type Pokemon known for its destructive nature.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png', 3),
('Lapras', 'A water/ice-type Pokemon with a gentle and calm nature. It is known for ferrying people across bodies of water.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png', 3),
('Ditto', 'A normal-type Pokemon known for its ability to transform into any other Pokemon. It can be found in the wild.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png', 5),
('Eevee', 'A normal-type Pokemon with the ability to evolve into various forms. It has multiple evolution options.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png', 5),
('Vaporeon', 'One of the evolved forms of Eevee, Vaporeon is a water-type Pokemon with the ability to manipulate water molecules.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png', 3),
('Jolteon', 'One of the evolved forms of Eevee, Jolteon is an electric-type Pokemon with sharp fur and the ability to generate electricity.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png', 8),
('Flareon', 'One of the evolved forms of Eevee, Flareon is a fire-type Pokemon with a mane of flames and the ability to control fire.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/136.png', 2),
('Porygon', 'A normal-type Pokemon that exists in cyberspace. It evolves into Porygon2 when traded holding an Up-Grade.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png', 5),
('Omanyte', 'A rock/water-type Pokemon that has been regenerated from a fossil. It evolves into Omastar.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png', 12),
('Omastar', 'The evolved form of Omanyte, Omastar is a rock/water-type Pokemon with a coiled shell and tentacles.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/139.png', 12),
('Kabuto', 'A rock/water-type Pokemon that has been regenerated from a fossil. It evolves into Kabutops.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/140.png', 12),
('Kabutops', 'The evolved form of Kabuto, Kabutops is a rock/water-type Pokemon with scythes for arms and powerful slashing abilities.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/141.png', 12),
('Aerodactyl', 'A rock/flying-type Pokemon that has been regenerated from a fossil. It Mega Evolves into Mega Aerodactyl using an Aerodactylite.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png', 12),
('Snorlax', 'A normal-type Pokemon known for its immense size and love for sleeping. It is often found blocking paths.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png', 5),
('Articuno', 'An ice/flying-type Legendary Pokemon that is said to appear to doomed travelers in icy mountain regions.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png', 14),
('Zapdos', 'An electric/flying-type Legendary Pokemon that is said to cause thunderstorms when it flaps its wings.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png', 8),
('Moltres', 'A fire/flying-type Legendary Pokemon that is said to be born from the flames of a volcano.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/146.png', 2),
('Dratini', 'A dragon-type Pokemon with a gentle and kind nature. It evolves into Dragonair.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/147.png', 16),
('Dragonair', 'The evolved form of Dratini, Dragonair is a dragon-type Pokemon with elegant and flowing serpentine movements.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/148.png', 16),
('Dragonite', 'The final evolution of Dratini, Dragonite is a powerful dragon/flying-type Pokemon known for its kind and helpful nature.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png', 16),
('Mewtwo', 'A psychic-type Legendary Pokemon known for its incredible psychic powers. It is the result of genetic manipulation.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png', 10),
('Mew', 'A psychic-type Mythical Pokemon said to contain the genetic code of every Pokemon. It is rarely seen.', 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png', 10);

