#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

fileList=$(git diff --cached --name-only :^package.json :^README.md :^frontend :^backend)

echo '----- Checking Root...'

if [ ! -z "$fileList" ]
then
  echo "error: Unauthorized modifications\n"

  echo "$fileList\n"

  echo "use 'git restore ...' to fix the problem"
  echo "(and ask your instructor why you should not change these files)\n"

  exit 1
fi

echo '----- Done!'

npm run lint
